"""
training/sft_warmup.py

v3 — Reasoning-Augmented SFT Warmup.

What changed:
  * Each synthetic example now contains a structured ANALYSIS chain
    (3 numbered steps) generated by an oracle that has access to the
    consequence simulator.
  * Examples cover the full proposal distribution: Engineer / Pilot /
    Commander / AdversarialBot, so the warmup teaches the model to
    distrust risk_level labels.
  * Targets the 3-section output format (ANALYSIS / DECISION / REASON)
    so GRPO can reward both the chain and the final token.
"""

import random
from typing import Dict, Any, List

# Heavy deps are guarded so this module is importable on macOS for tests.
_HAS_TRAIN_DEPS = False
_TRAIN_DEPS_ERROR = None
try:
    import torch
    from datasets import Dataset
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    _HAS_TRAIN_DEPS = True
except Exception as _e:
    _TRAIN_DEPS_ERROR = str(_e)
    torch = None
    _HAS_TRAIN_DEPS = False

from environment.specialist_bots import Engineer, Pilot, Commander, AdversarialBot
from environment.scoring_engine import simulate_consequence
from training.reward import is_proposal_dangerous, compute_violation_severity
from agents.overseer_model import OverseerModel

LIFE_SUPPORT = ["oxygen", "power", "hull_integrity"]


def build_oracle_analysis(state: Dict[str, Any], proposal: Dict[str, Any]) -> str:
    """Generates a 3-step oracle reasoning chain matching the assistant format."""
    projected = simulate_consequence(state, proposal)
    severity  = compute_violation_severity(state, proposal)
    dangerous = is_proposal_dangerous(state, proposal)
    is_adv    = proposal.get("true_risk", "") == "high"

    # Step 1: critical resources right now
    crit = [r for r in LIFE_SUPPORT if state.get(r, 100) < 35]
    if crit:
        s1 = f"Critical resources currently below 35%: {', '.join(crit)}."
    else:
        s1 = "All life-support resources currently above 35% safety margin."

    # Step 2: projected impact
    drops = [
        f"{r} {state.get(r,0):.0f}%→{projected.get(r,0):.0f}%"
        for r in LIFE_SUPPORT
        if projected.get(r, 100) < state.get(r, 100) - 1
    ]
    if drops:
        s2 = f"Approving would drive {'; '.join(drops)} (severity={severity:.2f})."
    else:
        s2 = f"Approving leaves life-support stable (severity={severity:.2f})."

    # Step 3: adversarial / contextual flag
    if is_adv:
        s3 = ("Proposal is labelled low-risk but masks a high-risk effect "
              "profile — this is a deceptive specialist.")
    elif dangerous:
        s3 = ("Even if individually plausible, the action collides with "
              "current resource margins and accelerates cascade failure.")
    else:
        s3 = ("Proposal is consistent with current margins and does not "
              "trigger any cascade thresholds.")

    decision = "VETO" if dangerous else "APPROVE"
    if dangerous and is_adv:
        reason = "Deceptive proposal — vetoing to preserve life support."
    elif dangerous:
        reason = "Approval would push a life-support resource below the 25% safety floor."
    else:
        reason = "Action is safe given current telemetry and projected state."

    return (
        f" {s1}\n"
        f"2. {s2}\n"
        f"3. {s3}\n"
        f"DECISION: {decision}\n"
        f"REASON: {reason}"
    )


def random_state(rng: random.Random) -> Dict[str, Any]:
    """Sample a plausible mid-mission station state."""
    return {
        "oxygen":         round(rng.uniform(15, 95), 1),
        "power":          round(rng.uniform(15, 95), 1),
        "fuel":           round(rng.uniform(15, 95), 1),
        "hull_integrity": round(rng.uniform(15, 95), 1),
        "crew_morale":    round(rng.uniform(20, 95), 1),
        "step_count":     rng.randint(0, 28),
    }


def generate_synthetic_data(num_samples: int = 400, seed: int = 7):
    """Build (prompt, response) pairs with full reasoning chains."""
    if not _HAS_TRAIN_DEPS:
        raise RuntimeError("`datasets` not available — run on Linux+CUDA.")

    rng  = random.Random(seed)
    bots = [Engineer(), Pilot(), Commander(), AdversarialBot()]
    bot_names = ["Engineer", "Pilot", "Commander", "AdversarialBot"]
    data = []

    # Pre-bake some explicit class balance: ~30% adversarial, rest evenly split
    for _ in range(num_samples):
        state    = random_state(rng)
        bot_idx  = rng.choices(range(4), weights=[0.25, 0.25, 0.20, 0.30])[0]
        bot      = bots[bot_idx]
        proposal = bot.generate_proposal(state)

        prompt   = OverseerModel.format_prompt(
            state, proposal, drift_log="None", specialist=bot_names[bot_idx]
        )
        response = build_oracle_analysis(state, proposal)
        data.append({"text": prompt + response + "<|eot_id|>"})

    return Dataset.from_list(data)


def run_sft():
    """SFT warmup on Llama-3.1-8B with QLoRA."""
    if not _HAS_TRAIN_DEPS:
        raise RuntimeError(
            f"Training deps missing. Failed import: {_TRAIN_DEPS_ERROR}\n"
            "Fix: Run Cell 1 (install) then go to Runtime → Restart session."
        )

    max_seq_length = 1536
    model_name     = "unsloth/llama-3.1-8b-bnb-4bit"

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name     = model_name,
        max_seq_length = max_seq_length,
        load_in_4bit   = True,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r              = 16,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                          "gate_proj", "up_proj", "down_proj"],
        lora_alpha     = 16,
        lora_dropout   = 0,
        bias           = "none",
        use_gradient_checkpointing = "unsloth",
        random_state   = 3407,
    )

    dataset = generate_synthetic_data(num_samples=400)

    trainer = SFTTrainer(
        model              = model,
        tokenizer          = tokenizer,
        train_dataset      = dataset,
        dataset_text_field = "text",
        max_seq_length     = max_seq_length,
        args = TrainingArguments(
            per_device_train_batch_size  = 2,
            gradient_accumulation_steps  = 4,
            warmup_steps                 = 5,
            num_train_epochs             = 1,
            learning_rate                = 2e-4,
            fp16                         = not torch.cuda.is_bf16_supported(),
            bf16                         = torch.cuda.is_bf16_supported(),
            logging_steps                = 10,
            optim                        = "adamw_8bit",
            weight_decay                 = 0.01,
            lr_scheduler_type            = "linear",
            seed                         = 3407,
            output_dir                   = "outputs",
            save_strategy                = "no",
        ),
    )

    print("[SFT] Starting reasoning-augmented warmup …")
    trainer.train()

    model.save_pretrained("overseer_lora_warmup")
    tokenizer.save_pretrained("overseer_lora_warmup")
    print("[SFT] Saved LoRA adapters → overseer_lora_warmup/")
    return model, tokenizer


if __name__ == "__main__":
    if torch is not None and torch.cuda.is_available():
        run_sft()
    else:
        print("CUDA not available. Skipping training.")
