import torch
from typing import Dict, Any
from unsloth import FastLanguageModel

class OverseerModel:
    """
    The Overseer LLM agent responsible for APPROVING or VETOING specialist proposals.
    Uses Unsloth for optimized Llama-3.1 inference and fine-tuning.
    """
    
    def __init__(self, model_name: str = "unsloth/llama-3.1-8b-bnb-4bit"):
        """
        Initializes the Overseer agent with a specific model reference.
        
        Args:
            model_name: The HuggingFace model path (defaulting to Unsloth's 4-bit Llama-3.1).
        """
        self.model_name = model_name
        self.model = None
        self.tokenizer = None
        self.max_seq_length = 2048

    def load_model(self, use_4bit: bool = True):
        """
        Loads the model and tokenizer using Unsloth's optimized loader.
        
        Args:
            use_4bit: Whether to load the model in 4-bit precision for memory efficiency.
        
        Returns:
            A tuple of (model, tokenizer).
        """
        self.model, self.tokenizer = FastLanguageModel.from_pretrained(
            model_name=self.model_name,
            max_seq_length=self.max_seq_length,
            load_in_4bit=use_4bit,
            dtype=None,  # Automatically detects platform dtype (Float16/Bfloat16)
        )
        
        # Prepare for inference (enables faster generation)
        FastLanguageModel.for_inference(self.model)
        
        return self.model, self.tokenizer

    def format_prompt(self, state: Dict[str, Any], proposal: Dict[str, Any]) -> str:
        """
        Formats the current station state and the specialist proposal into a strict directive prompt.
        
        Args:
            state: Current environment state.
            proposal: The proposal dictionary generated by a specialist.
            
        Returns:
            A string prompt following the Llama-3 instruction format.
        """
        prompt = f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are the Space Station Overseer. Your goal is survival until step 30.
You must analyze the current station state and the specialist's proposal.
Critically evaluate if the proposal's gains outweigh the costs and risks.
Output ONLY 'APPROVE' or 'VETO'. Do not provide any explanation or reasoning.<|eot_id|><|start_header_id|>user<|end_header_id|>

STATION STATE:
{state}

SPECIALIST PROPOSAL:
- Type: {proposal.get('type', 'N/A')}
- Description: {proposal.get('description', 'No description provided.')}
- Potentital Effects: {proposal.get('effects', {})}

Should I APPROVE or VETO this proposal?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

"""
        return prompt

    def decide(self, state: Dict[str, Any], proposal: Dict[str, Any]) -> str:
        """
        Runs inference on the model to determine the decision for a given proposal.
        
        Args:
            state: Current station state.
            proposal: Specialist's proposal dictionary.
            
        Returns:
            'APPROVE' or 'VETO'.
        """
        if not self.model or not self.tokenizer:
            raise RuntimeError("Overseer model not loaded. Call load_model() first.")

        # Format prompt according to model training template
        prompt = self.format_prompt(state, proposal)
        inputs = self.tokenizer([prompt], return_tensors="pt").to("cuda")

        # Generate a small number of tokens for binary decision
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs, 
                max_new_tokens=4, 
                use_cache=True,
                pad_token_id=self.tokenizer.eos_token_id
            )
        
        # Extract the assistant's response part
        full_response = self.tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
        
        # Post-process response (strip whitespace and handle casing)
        # We look for the prediction after the prompt section
        decision_text = full_response.split("assistant")[-1].strip().upper()
        
        if "APPROVE" in decision_text:
            return "APPROVE"
        elif "VETO" in decision_text:
            return "VETO"
        else:
            # Fallback if model output is ambiguous
            return "VETO"
